version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: commitly_postgres
    environment:
      POSTGRES_DB: commitly
      POSTGRES_USER: commitly
      POSTGRES_PASSWORD: commitly
      PGPORT: "5433"
    ports:
      - "5433:5433"
    volumes:
      - commitly_data:/var/lib/postgresql/data

volumes:
  commitly_data: